In [11]:
import pandas as pd
import numpy as np
import json
from tqdm import tqdm
import matplotlib.pyplot as plt
from PIL import Image
import matplotlib.patches as patches
import numpy as np
import seaborn as sns
import os
import shutil
import re
from sklearn.model_selection import train_test_split

train, val, test dataset 이미지 분포를 class, orientation별로 확인하는 코드입니다 \
data_raw도 다운받아 서버에 포함되어있다면, 아래 주석들 모두 해제 후 진행

In [12]:
#todo - dir 수정

# data_raw 받았다면 아래 주석 해제
# img_dir = '/opt/ml/final_project/data_raw/images/'
# ann_dir = '/opt/ml/final_project/data_raw/json/'

train_img_dir = '/opt/ml/final_project/data/train/images/'
train_ann_dir = '/opt/ml/final_project/data/train/json/'

val_img_dir = '/opt/ml/final_project/data/val/images/'
val_ann_dir = '/opt/ml/final_project/data/val/json/'

test_img_dir = '/opt/ml/final_project/data/test/images/'
test_ann_dir = '/opt/ml/final_project/data/test/json/'

In [13]:
# data_raw 받았다면 아래 주석 해제
# fileids = []
# class_num = []
# orient = []
# img_fileids = []

# for idx, img_fileid in enumerate(os.listdir(img_dir)):
    
#     fileid = img_fileid.split('.')[0]
#     #fileid = re.match('\w+_\d+', img_fileid).group(0)
#     ann_fileid = fileid+'.json'

#     img_fileids.append(img_fileid)
#     fileids.append(fileid)
#     with open(ann_dir+ann_fileid, "r", encoding="utf8") as f:
#         contents = f.read() # string 타입
#         json_data = json.loads(contents)
#         class_num.append(json_data['objects'][0]['classTitle'])
        
#         tags = json_data['objects'][0]['tags']
#         for idx, tag in enumerate(tags):
#             if tag['name'] == 'orientation':
#                 orient.append(tag['value'])
# df = pd.DataFrame()
# df['fileid'] = fileids
# df['img'] = img_fileids
# df['class_num'] = class_num
# df['orient'] = orient
      
fileids = []
class_num = []
orient = []
img_fileids = []

for idx, img_fileid in enumerate(os.listdir(train_img_dir)):
    
    fileid = img_fileid.split('.')[0]
    #fileid = re.match('\w+_\d+', img_fileid).group(0)
    ann_fileid = fileid+'.json'

    img_fileids.append(img_fileid)
    fileids.append(fileid)
    with open(train_ann_dir+ann_fileid, "r", encoding="utf8") as f:
        contents = f.read() # string 타입
        json_data = json.loads(contents)
        class_num.append(json_data['objects'][0]['classTitle'])
        
        tags = json_data['objects'][0]['tags']
        for idx, tag in enumerate(tags):
            if tag['name'] == 'orientation':
                orient.append(tag['value'])

df_train = pd.DataFrame()
df_train['fileid'] = fileids
df_train['img'] = img_fileids
df_train['class_num'] = class_num
df_train['orient'] = orient

fileids = []
class_num = []
orient = []
img_fileids = []

for idx, img_fileid in enumerate(os.listdir(val_img_dir)):
    
    fileid = img_fileid.split('.')[0]
    #fileid = re.match('\w+_\d+', img_fileid).group(0)
    ann_fileid = fileid+'.json'

    img_fileids.append(img_fileid)
    fileids.append(fileid)
    with open(val_ann_dir+ann_fileid, "r", encoding="utf8") as f:
        contents = f.read() # string 타입
        json_data = json.loads(contents)
        class_num.append(json_data['objects'][0]['classTitle'])
        
        tags = json_data['objects'][0]['tags']
        for idx, tag in enumerate(tags):
            if tag['name'] == 'orientation':
                orient.append(tag['value'])

df_val = pd.DataFrame()
df_val['fileid'] = fileids
df_val['img'] = img_fileids
df_val['class_num'] = class_num
df_val['orient'] = orient

fileids = []
class_num = []
orient = []
img_fileids = []

for idx, img_fileid in enumerate(os.listdir(test_img_dir)):
    
    fileid = img_fileid.split('.')[0]
    #fileid = re.match('\w+_\d+', img_fileid).group(0)
    ann_fileid = fileid+'.json'

    img_fileids.append(img_fileid)
    fileids.append(fileid)
    with open(test_ann_dir+ann_fileid, "r", encoding="utf8") as f:
        contents = f.read() # string 타입
        json_data = json.loads(contents)
        class_num.append(json_data['objects'][0]['classTitle'])
        
        tags = json_data['objects'][0]['tags']
        for idx, tag in enumerate(tags):
            if tag['name'] == 'orientation':
                orient.append(tag['value'])

df_test = pd.DataFrame()
df_test['fileid'] = fileids
df_test['img'] = img_fileids
df_test['class_num'] = class_num
df_test['orient'] = orient

In [14]:
count = pd.concat([df_train.groupby(['class_num']).count().rename(columns={'img':'train'})['train'],df_val.groupby(['class_num']).count().rename(columns={'img':'val'})['val'],df_test.groupby(['class_num']).count().rename(columns={'img':'test'})['test']],axis=1)
# data_raw 받았다면 아래 주석 해제
# count = pd.concat([df_train.groupby(['class_num']).count().rename(columns={'img':'train'})['train'],df_val.groupby(['class_num']).count().rename(columns={'img':'val'})['val'],df_test.groupby(['class_num']).count().rename(columns={'img':'test'})['test'],df.groupby(['class_num']).count().rename(columns={'img':'total'})['total']],axis=1)
count.loc[4] = pd.array(pd.DataFrame.sum(count))
count.rename(index={4:'sum'},inplace=True)
count

           train  val  test
class_num
0            333   80    40
1            481   83    41
2             31   18     9
3            158   59    31
sum         1003  240   121

In [15]:
pd.concat([df_train.groupby(['class_num','orient']).count().rename(columns={'img':'train'})['train'],df_val.groupby(['class_num','orient']).count().rename(columns={'img':'val'})['val'],df_test.groupby(['class_num','orient']).count().rename(columns={'img':'test'})['test']],axis=1).replace(np.NaN,0).astype(int)
# data_raw 받았다면 아래 주석 해제
# pd.concat([df_train.groupby(['class_num','orient']).count().rename(columns={'img':'train'})['train'],df_val.groupby(['class_num','orient']).count().rename(columns={'img':'val'})['val'],df_test.groupby(['class_num','orient']).count().rename(columns={'img':'test'})['test'],df.groupby(['class_num','orient']).count().rename(columns={'img':'total'})['total']],axis=1).replace(np.NaN,0).astype(int)

                  train  val  test
class_num orient
0         Front      60   15     7
          Rear       57   13     7
          Side      216   52    26
1         Front      95   16     8
          Rear       63   11     5
          Side      323   56    28
2         Front       6    0     0
          Rear        6    4     2
          Side       19   14     7
3         Front      22    9     5
          Rear       22    8     4
          Side      114   42    22